language: php
sudo: false

php:
- 5.5.9
- 5.6
- 7

services:
- redis-server
- mongodb

before_script:
- pecl install mongodb
- composer self-update
- composer install --no-interaction

script:
- vendor/bin/phpunit

matrix:
  fast_finish: true